### ISSUE TITLE
Disable buttons

### ISSUE THREAD

**Issue by PixelmonPRO** [Team-Fruit/ServerObserver#1]
Hello! Very cool mod!
I would very much like to add the function of disabling buttons.
Example: i disconnected server, and i go in main menu (or gui have one button, back to main menu), disable button on server list.

**Comment by Kamesuta** [comment]
You can disable it by pressing the button in the upper right.
I did not understand the meaning of your question.
Please tell me more in detail.
![Toggle Mode](https://i.gyazo.com/6109c014ca368e1b8b27d2e09faacf2b.gif)

**Comment by PixelmonPRO** [comment]
Sorry that I did not reply for a while.
These buttons
<img width="1440" alt="2017-11-24 14 16 55" src="https://user-images.githubusercontent.com/26658563/33208423-80b12bac-d122-11e7-95dc-33bcca4db2b3.png">
I have my own client (many use modpacks with Technic launchers, and this setting will also work)
