### ISSUE TITLE
[Suggestion] Check box for starting on the multiplayer screen

### ISSUE THREAD

**Issue by TheRandomLabs** [Team-Fruit/ServerObserver#5]
Coupled with autologin, this could be especially useful for modpacks that take some time to load. You could leave the pack loading and come back to play on a server immediately.

**Comment by Kamesuta** [comment]
That's a good idea!
I wanted to implement it if requested.
We will implement it, there are 3 ways.
① When name and address are written in config, it is always connected automatically.
② A configuration like "default.cfg" is prepared and set at the first start
③ Write server list in config like "server.cfg" and write reference to server list in config.

**Comment by TheRandomLabs** [comment]
Sounds great!

**Comment by Kamesuta** [comment]
Which is the best?

**Comment by Kamesuta** [comment]
That's done!
First, please update to 1.0.2.x.
https://github.com/Team-Fruit/ServerObserver/releases
Next, please do the following operation
https://github.com/Team-Fruit/ServerObserver/wiki/servers.json

**Comment by TheRandomLabs** [comment]
This is great, but a checkbox would still be useful if players are not using a modpack. I will use servers.json though if you don't want to implement that.

**Comment by Kamesuta** [comment]
servers.json will only be used when ServerObserver is started for the first time. After servers.json is used, "Miscellaneous/InitServers" in config will be false, so if you change it to true, it will be used again.

**Comment by TheRandomLabs** [comment]
I just tested it, and while it works fine (and is a great feature), I think you misunderstood me. What I was suggesting was a checkbox in the Multiplayer screen. When this checkbox is enabled, instead of starting in the main menu, the game starts in the Multiplayer screen.

**Comment by Kamesuta** [comment]
Implemented! I think that all of your wishes have been granted. Please be aware that the auto login function has been moved to "config" from "servers.json".

**Comment by TheRandomLabs** [comment]
Thanks so much. I'll check it out soon.
