### ISSUE TITLE
Does not function - unable to click button.

### ISSUE THREAD

**Issue by ProsperCraft** [Team-Fruit/ServerObserver#6]
The button is missing its label - 
https://i.gyazo.com/5ae55970659e574babe3caa9685dae44.png

Is the reauth mod conflicting with this mod?  

I can't click the button to open the gui.

Here is my config - https://gist.github.com/ProsperCraft/dde0bb1c44018debc1daa492754f0413

IT doesn't start on the Multiplayer tab, it doesn't try to log in, it doesn't try to reconnect.

Modpack - https://minecraft.curseforge.com/projects/towncraft

**Comment by Kamesuta** [comment]
Thank you for the report. I will check it.

**Comment by Kamesuta** [comment]
Oh no.
Your ModPack contains an **incorrect** version of ServerObserver.
You need to use the appropriate version, or "Universal" version.
Please note that the version of Mod is "ServerObserver-${mcversion}-${version}-universal.jar".
![TownCraft](https://i.gyazo.com/bbf7905a42974cac2a711816ff37c49f.png)
